# Generated by Django 5.1.3 on 2025-01-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_purchase_items_alter_ingredient_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='items',
            field=models.ManyToManyField(through='inventory.PurchaseItem', to='inventory.menuitem'),
        ),
    ]
